### ISSUE TITLE
Program Warning

### ISSUE THREAD

**Issue by Renjh-rab** [rehmanali1994/WaveformInversionUST#1]
Hi Rehman Ali,

Thank you so much for the open-source program you've provided. We're currently studying your full waveform inversion program but have encountered some issues. The main problem is that we followed the steps and used your code to run the forward time-domain data on the breast-CT model using K-WAVE. However, when we run the MultiFrequencyWaveformInvkWave.m script for inversion, we keep getting the following warning. Both the velocity model and the attenuation model values are shown as NaN and do not change at all. Could you help us understand what might be causing this issue? We use Matlab2020a, CUDA 11.2 and Visual Studio2017.
Looking forward to receiving your reply.
![Program screenshot](https://github.com/rehmanali1994/WaveformInversionUST/assets/153473680/d0e2992c-af13-4504-b804-9b3b24a4f434)

**Comment by Renjh-rab** [comment]
The NVIDIA RTX A5000 is used for the graphics card

**Comment by YujiaFMILab** [comment]
Hi Rehman Ali,

I am also facing the same issue.
Would you happen to know the possible reason for it so I can debug it more quickly? Thanks for your help!
