### ISSUE TITLE
Question about stepsize calculation in the nonlinear conjugate gradient method

### ISSUE THREAD

**Issue by lzbmeee** [rehmanali1994/WaveformInversionUST#2]
Thank you for open sourcing your code. 
I'm confused with the stepsize formula (8) in the paper. The code comments says it's linear approximation of exact line search.
Would you please educate me how to derive it ?

**Comment by rehmanali1994** [comment]
![IMG_0148](https://github.com/user-attachments/assets/d1e2027f-4c8c-4214-a534-2fe5ca06cbd9)
