### ISSUE TITLE
A question about step size calculation in the conjugate gradient method

### ISSUE THREAD

**Issue by lzbmeee** [rehmanali1994/WaveformInversionUST#3]
Thank you for open sourcing your code !
I'm confused about the step size formula (8) in the paper. The code comment says it's a linear approximation of exact line search method. Could you educate me how to derive it?
![Snipaste_2024-08-14_15-15-24](https://github.com/user-attachments/assets/22f4f237-4605-4d65-8b4a-33914f0b2e09)
Thanks again.

**Comment by rehmanali1994** [comment]
![IMG_0148](https://github.com/user-attachments/assets/ca44d9df-98de-42a7-b0a7-946d3313c113)
